#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: bevel-samples
  description: Bevel-Samples repository holds sample reference applications that can be deployed on bevel deployed blockchain networks
  homepage: https://github.com/hyperledger/bevel-samples
  default_branch: main
  has_downloads: true
  has_issues: true
  has_projects: true
  has_wiki: true
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
