#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: bevel-samples
  description: An automation framework for rapidly and consistently deploying production-ready DLT platforms
  homepage: https://github.com/hyperledger/bevel
  default_branch: main
  has_downloads: true
  has_issues: true
  has_projects: true
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
