##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    run: {{ .Values.nodeName }}
    app.kubernetes.io/name: {{ .Values.nodeName }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: {{ .Values.nodeName }}
  ports:
  - port: {{ .Values.frontend.nodePorts.port }}
    targetPort: {{ .Values.frontend.nodePorts.targetPort }}
    protocol: TCP
{{- if eq $.Values.proxy.provider "ambassador" }}
---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: {{ .Values.proxy.peer_name }}web-tlscontext
  namespace: {{ .Values.metadata.namespace }}
spec:
  hosts:
  - {{ .Values.proxy.peer_name }}web.{{ .Values.proxy.external_url_suffix }}
  secret: {{ .Values.proxy.ambassador_secret }}.{{ .Values.metadata.namespace }}
  secret_namespacing: true
  min_tls_version: v1.2
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: {{ .Values.proxy.peer_name }}web-mapping
  namespace: {{ .Values.metadata.namespace }}
spec:
  prefix: /
  host: {{ .Values.proxy.peer_name }}web.{{ .Values.proxy.external_url_suffix }}
  service: {{ .Values.proxy.peer_name }}-frontend.{{ .Values.metadata.namespace }}:{{ .Values.frontend.nodePorts.port }}
{{ end }}   
{{- if eq $.Values.proxy.provider "haproxy" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.nodeName }}
  namespace:  {{ $.Values.metadata.namespace }}
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  tls:
  - hosts:
    - {{ .Values.proxy.peer_name }}web.{{ .Values.proxy.external_url_suffix }}
    secretName: {{ .Values.proxy.ambassador_secret }}
  rules:
  - host: {{ .Values.proxy.peer_name }}web.{{ .Values.proxy.external_url_suffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.proxy.peer_name }}-frontend
            port:
              number: {{ .Values.frontend.nodePorts.port }}
{{- end }}
